### ISSUE TITLE
swiper changedTouches[0] 没有东西

### ISSUE THREAD

**Issue by luofanrain** [remaxjs/awesome-remax#3]
![image](https://user-images.githubusercontent.com/23522554/103518075-19db2380-4eae-11eb-8fed-98ed24e2e775.png)
![image](https://user-images.githubusercontent.com/23522554/103518131-28c1d600-4eae-11eb-847c-ae37f5ed185f.png)
![image](https://user-images.githubusercontent.com/23522554/103517944-e5676780-4ead-11eb-9158-f29998581c70.png)

swiper  handleTouchEnd 时间执行时e.changedTouches为空数组，此时取0值为undefind, 取undefind的pageX会报错
![image](https://user-images.githubusercontent.com/23522554/103518400-ac7bc280-4eae-11eb-8585-fd063dc2d97f.png)

**Comment by yesmeck** [comment]
请提到 https://github.com/remaxjs/remax/issues
